### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by confluence** [confluence/python-textbok#4]
This project is not currently building on RTD. It was migrated here from BitBucket, and even before the migration there was an issue with the build (IIRC because of broken dependencies). I'm not actively maintaining this project, but I have just merged some contributions, so this really should be fixed.

To be done:

- [ ] Hook up RTD to this GitHub repo
- [ ] Fix whatever was wrong with the build

**Comment by KwesiJoe** [comment]
@confluence I think only you can Hook up RTD to this GitHub repo. then someone else can look at fixing the build

**Comment by confluence** [comment]
The build has been fixed.
